{
 "title": "Pizza Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "serviceLatency_milliseconds_total",
     "legendFormat": "Latency (ms)"
    }
   ]
  },
  {
   "title": "Order Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "pizzaLatency_milliseconds_total",
     "legendFormat": "Latency (ms)"
    }
   ]
  },
  {
   "title": "Revenue per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "revenuePerMinute_total", "legendFormat": "Bitcoin" }
   ]
  },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "pizzasSoldPerMinute_total", "legendFormat": "Sold" },
    { "expr": "pizzaCreationFailure_total", "legendFormat": "Failed" }
   ]
  },
  {
   "title": "CPU and Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_ratio", "legendFormat": "CPU" },
    { "expr": "memory_ratio", "legendFormat": "Memory" }
   ]
  },
  {
   "title": "Authentication Attempts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "authSuccess_total{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "Success"
    },
    { "expr": "authFailure_total", "legendFormat": "Failure" }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "activeUsers_total", "legendFormat": "Active Users" }
   ]
  },
  {
   "title": "HTTP Requests By Method per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "requests_per_minute_total{method=\"GET\"}",
     "legendFormat": "GET"
    },
    {
     "expr": "requests_per_minute_total{method=\"POST\"}",
     "legendFormat": "POST"
    },
    {
     "expr": "requests_per_minute_total{method=\"PUT\"}",
     "legendFormat": "PUT"
    },
    {
     "expr": "requests_per_minute_total{method=\"DELETE\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "timeseries",
   "description": "All HTTPS requests ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "requests_total", "legendFormat": "{{endpoint}}" }
   ]
  }
 ]
}